# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lanche' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
  # Pods for Lanche

  target 'LancheTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LancheUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
